version: '3.9'

services:
  app:
    platform: linux/x86_64
    image: id.zenness/php-excercise:latest
    tty: true
    volumes:
      - ./demo:/var/www/html/
    env_file:
      - environment.env
    ports:
      - "8080:8080"